[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn aula_inteligente.wsgi --log-file -"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[nixpacks]
python-version = "3.11"

